language: go

env:
  global:
    - GO111MODULE=on
    - TEXTIMG_EMOJI_DIR=/tmp/noto-emoji/png/128
    - TEXTIMG_FONT_FILE=/usr/share/fonts/TTF/HackGen-Regular.ttf

before_script:
  - sudo install -d -o $USER -g $USER -m 0777 /images
  - go build
  - git clone https://github.com/googlefonts/noto-emoji /tmp/noto-emoji

script:
  - go build
  - go test -cover ./...
  - ./tester.sh
  - ./textimg "t.png" -s
  - ./textimg "t.gif" -sa

after_script:
  - [ -e /images/t.png ]
  - [ -e /images/t.gif ]
